main: com.astrainteractive.astranpcs.AstraNPCS
name: '${name}'
version: '${version}'
description: '${description}'
author: MakeevRoman
authors: [ MakeevRoman ]
website: AstraInteractive.ru
api-version: 1.17
softdepend: [ProtocolLib]
depend: []
commands:
  anpc:
