main: com.astrainteractive.astranpcs.AstraNPCS
name: AstraNPCS
version: '${project.version}'
author: MakeevRoman
authors: [ MakeevRoman ]
website: AstraInteractive.ru
api-version: 1.17
softdepend: []
depend: [ProtocolLib]
commands:
  anpc:
